export const backgroundLayer1 = new Image()
backgroundLayer1.src = "../img/backgroundLayers/layer-1.png"
export const backgroundLayer2 = new Image()
backgroundLayer2.src = "../img/backgroundLayers/layer-2.png"
export const backgroundLayer3 = new Image()
backgroundLayer3.src = "../img/backgroundLayers/layer-3.png"
export const backgroundLayer4 = new Image()
backgroundLayer4.src = "../img/backgroundLayers/layer-4.png"
export const backgroundLayer5 = new Image()
backgroundLayer5.src = "../img/backgroundLayers/layer-5.png"
