export const EFFECT_CONSTANTS = {
  DUST: {
    SIZE_MIN: 15,
    SIZE_MAX: 25,
    SPEED_X_MIN: 0,
    SPEED_X_MAX: 1,
    SPEED_Y_MIN: 0,
    SPEED_Y_MAX: 1,
    COLOR: "rgba(0, 0, 0, 0.2)",
  },
  FIRE: {
    SIZE_MIN: 50,
    SIZE_MAX: 150,
    SPEED_X: 1,
    SPEED_Y: 1,
    VA_MIN: -0.1,
    VA_MAX: 0.1,
    IMAGE: "fire",
  },
  SPLASH: {
    SIZE_MIN: 100,
    SIZE_MAX: 200,
    SPEED_X_MIN: -4,
    SPEED_X_MAX: 2,
    SPEED_Y_MIN: 2,
    SPEED_Y_MAX: 4,
    GRAVITY_INCREMENT: 0.1,
    IMAGE: "fire",
  },
};
